### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by danielhjacobs** [AurorNZ/paths-filter#8]
This is warning: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by danielhjacobs** [comment]
Note that https://github.com/dorny/paths-filter has been updated to use Node 20 already.

**Comment by CodeBlanch** [comment]
I am also getting a warning: https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/7673587827/attempts/1?pr=5262

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: AurorNZ/paths-filter@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

@Obi-Dann Something easy to fix or no?

**Comment by Obi-Dann** [comment]
@CodeBlanch @danielhjacobs Done, you can use `paths-filter@v4` or `paths-filter@v4.0.0`. Please let me know if there're any issues with the release.
